config/routes.rb
Rails.application.routes.draw do

  resources :depositemoneys

  resources :deposites

  get 'profile/index'

  get 'home/index'

  devise_for :users
      root to: "home#index"

end

app/models/deposite.rb
class Deposite < ActiveRecord::Base
	  belongs_to :user
  validates :user_id, presence: true
  validates :deposite_amt, presence: true
  # validates :deposite_amt, format: { with: /\A\d+\z/, message: "Integer only. No sign allowed." }
  validates :deposite_amt, numericality: { greater_than: 0 }



	def user_balance
		user.balance
	end
end

app/models/depositemoney.rb
class Depositemoney < ActiveRecord::Base
    # validates :balance, :numericality => {:only_integer => true}
    # validates :balance, presence: true
      validates :balance, presence: true
             # validates :balance, :inclusion => {:in => [1,2]}
      # validates :balance, format: { with: /\A\d+\z/, message: "Integer only. No sign allowed." }
        validates :balance, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :deposites

      validates :name, presence: true
      validates :address, presence: true
      validates :balance, presence: true
      validates :address, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resource_or_scope)
	 	profile_index_path
	end


 

 protected

 def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:name, :address, :balance, :email, :u_id)
    devise_parameter_sanitizer.for(:account_update).push(:name, :address, :balance, :email, :u_id)
 end

end

app/controllers/depositemoneys_controller.rb
class DepositemoneysController < ApplicationController
  before_action :set_depositemoney, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @depositemoneys = Depositemoney.all
    respond_with(@depositemoneys)
  end

  def show
    respond_with(@depositemoney)
  end

  def new
    @depositemoney = Depositemoney.new
    respond_with(@depositemoney)
  end

  def edit
  end

  def create

       if depositemoney_params.present? and 
              @depositemoney = Depositemoney.new(depositemoney_params)
              @depositemoney.save
              @user = User.find current_user.id
              @balance = @user.balance.to_i
              @deposite_money = depositemoney_params[:balance].to_i
              total_deposite = @deposite_money + @balance

              if total_deposite > 0
                abc = @user.update_attribute(:balance, total_deposite) 
              end  
              redirect_to profile_index_path
       end
  end

  def update
    @depositemoney.update(depositemoney_params)
    respond_with(@depositemoney)
  end

  def destroy
    @depositemoney.destroy
    respond_with(@depositemoney)
  end

  private
    def set_depositemoney
      @depositemoney = Depositemoney.find(params[:id])
    end

    def depositemoney_params
      params.require(:depositemoney).permit(:balance, :u_id)
    end
end

app/controllers/deposites_controller.rb
class DepositesController < ApplicationController
  before_action :set_deposite, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @deposites = Deposite.all
    respond_with(@deposites)
  end

  def show
    respond_with(@deposite)
  end

  def new
    @users = User.all
    @deposite = Deposite.new
    respond_with(@deposite)
  end

  def edit
  end

def create
if deposite_params.present?
    @deposite = Deposite.new(deposite_params)
    @deposite.save
    
    @user = User.find deposite_params[:user_id]
    @balance = @user.balance.to_i
    @deposite_money = deposite_params[:deposite_amt].to_i

          @user = User.find deposite_params[:user_id]
          @balance = @user.balance.to_i
          @deposite_money = deposite_params[:deposite_amt].to_i
         
          total_deposite = @deposite_money + @balance

          # abort total_deposite.inspect
          if total_deposite > 0
              abc = @user.update_attribute(:balance, total_deposite)
          end
          @user = User.find current_user.id
          deduct_bal = @balance - @deposite_money
          if deduct_bal > 0
              xyz = @user.update_attribute(:balance, deduct_bal)
          end          
          
      redirect_to profile_index_path
end      
end

  def update
    @deposite.update(deposite_params)
    respond_with(@deposite)
  end

  def destroy
    @deposite.destroy
    respond_with(@deposite)
  end

  private
    def set_deposite
      @deposite = Deposite.find(params[:id])
    end

    def deposite_params
      params.require(:deposite).permit(:user_id, :deposite_amt, :u_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/depositemoneys_helper.rb
module DepositemoneysHelper
end

app/helpers/deposites_helper.rb
module DepositesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/depositemoneys/_form.html.erb
<%= form_for(@depositemoney) do |f| %>
  <% if @depositemoney.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@depositemoney.errors.count, "error") %> prohibited this depositemoney from being saved:</h2>

      <ul>
      <% @depositemoney.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :balance %><br> 
    <%= f.number_field :balance, :id => "balance" %> Maximum U can Add 10000/-
  </div>
  <%= f.hidden_field :u_id, :value => current_user.id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<script type="text/javascript">
$(document).ready(function () {
    $('#balance').keyup(function(){
        if ($(this).val() > 10000){
          alert("Maximum U can Add 10,000/-");
        }
    });
    $('#balance').keyup(function(){
        if ($(this).val() < 0){
          alert("Minimum U can Add 1 Rs./-");
        }
    });
});
</script>

app/views/depositemoneys/edit.html.erb
<h1>Editing depositemoney</h1>

<%= render 'form' %>

<%= link_to 'Show', @depositemoney %> |
<%= link_to 'Back', depositemoneys_path %>

app/views/depositemoneys/index.html.erb
<h1>Listing depositemoneys</h1>

<table>
  <thead>
    <tr>
      <th>Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @depositemoneys.each do |depositemoney| %>
      <tr>
      <% if depositemoney.u_id == current_user.id %>
        <td><%= depositemoney.balance %></td>
        <td><%= link_to 'Show', depositemoney %></td>
        <td><%#= link_to 'Edit', edit_depositemoney_path(depositemoney) %></td>
        <td><%= link_to 'Destroy', depositemoney, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>  
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Depositemoney', new_depositemoney_path %>

app/views/depositemoneys/new.html.erb
<h1>New depositemoney</h1>

<%= render 'form' %>

<%= link_to 'Back', depositemoneys_path %>

app/views/depositemoneys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Balance:</strong>
  <%= @depositemoney.balance %>
</p>

<%= link_to 'Edit', edit_depositemoney_path(@depositemoney) %> |
<%= link_to 'Back', depositemoneys_path %>

app/views/deposites/_form.html.erb
<%= form_for(@deposite) do |f| %>
  <% if @deposite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deposite.errors.count, "error") %> prohibited this deposite from being saved:</h2>

      <ul>
      <% @deposite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br>
    <%= f.select :user_id, @users.collect { |u| [u.name, u.id] } %>
  </div>
  <div class="field">
    <%= f.label :deposite_amt %><br>
    <%= f.number_field :deposite_amt, :id => "deposite_amt" %>
  </div>
    <%= f.hidden_field :u_id, :value => current_user.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">
$(document).ready(function () {
  // alert(1)
    $('#deposite_amt').keyup(function(){
          // alert(2)
        if ($(this).val() > 10000){
          alert("Maximum U Can Transfer 10,000/-");
        }
    });
    $('#deposite_amt').keyup(function(){
        if ($(this).val() < 0){
          alert("Minimum U can Add 1 Rs./-");
        }
    });
});
</script>

app/views/deposites/edit.html.erb
<h1>Editing deposite</h1>

<%= render 'form' %>

<%= link_to 'Show', @deposite %> |
<%= link_to 'Back', deposites_path %>

app/views/deposites/index.html.erb
<h1>Listing deposites</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Deposite amt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deposites.each do |deposite| %>
      <tr>
        <% if deposite.u_id == current_user.id %>
            <td><%= current_user.name %></td>
            <td><%= deposite.deposite_amt %></td>
            <td><%= link_to 'Show', deposite %></td>
            <td><%#= link_to 'Edit', edit_deposite_path(deposite) %></td>
            <td><%= link_to 'Destroy', deposite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deposite', new_deposite_path %>

app/views/deposites/new.html.erb
<h1>New deposite</h1>

<%= render 'form' %>

<%= link_to 'Back', deposites_path %>

app/views/deposites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @deposite.user_id %>
</p>

<p>
  <strong>Deposite amt:</strong>
  <%= @deposite.deposite_amt %>
</p>

<%= link_to 'Edit', edit_deposite_path(@deposite) %> |
<%= link_to 'Back', deposites_path %>

app/views/home/index.html.erb
 <section>
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-6 order-2">
            <div class="p-5">
              <img class="img-fluid rounded-circle" src="http://c1.vgtstatic.com/thumb/2/0/208391-v1-xl/bank-of-montreal-head-office-montreal.jpg" alt="">
            </div>
          </div>
          <div class="col-md-6 order-1">
            <div class="p-5">
              <h2 class="display-4">For those about to rock Online Banking...</h2>
              <p>Online banking, also known as internet banking, e-banking or virtual banking, is an electronic payment system that enables customers of a bank or other financial institution to conduct a range of financial transactions through the financial institution's website. The online banking system will typically connect to or be part of the core banking system operated by a bank and is in contrast to branch banking which was the traditional way customers accessed banking services.</p>
              <p>Online banking, also known as internet banking, e-banking or virtual banking, is an electronic payment system that enables customers of a bank or other financial institution to conduct a range of financial transactions through the financial institution's website. The online banking system will typically connect to or be part of the core banking system operated by a bank and is in contrast to branch banking which was the traditional way customers accessed banking services.</p>
              <p>Online banking, also known as internet banking, e-banking or virtual banking, is an electronic payment system that enables customers of a bank or other financial institution to conduct a range of financial transactions through the financial institution's website. The online banking system will typically connect to or be part of the core banking system operated by a bank and is in contrast to branch banking which was the traditional way customers accessed banking services.</p>
            </div>
          </div>
        </div>
      </div>
    </section>
          <hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BankApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <% if flash[:alert] %>
      <div id="alert">
         <%= flash[:alert] %> 
      </div>
<% end %>
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
       
        <nav>
          <a class="navbar-brand" href="/">Online Banking Managment System</a>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                <li><%= link_to "Home", '/profile/index' %></li>
            <% else %>
                <li><%= link_to "Home", '/' %></li>
            <% end %>    
                <% if user_signed_in? %>
                  <li>
                  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
                  </li>
                  <% else %>
                  <li>
                  <%= link_to('Login', new_user_session_path)  %>  
                  </li>
                <% end %>
                <% if user_signed_in? %>
                  <li>
                  <%= link_to('Edit registration', edit_user_registration_path) %>
                  </li>
                <% else %>
                  <li>
                  <%= link_to('Register', new_user_registration_path)  %>
                  </li>
                <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

<%= yield %>
</div>
</body>
</html>